function createWebviewMedia(vscode, webview, extensionUri) {
  const mediaRoot = vscode.Uri.joinPath(extensionUri, "media");
  const mediaUri = (name) => webview.asWebviewUri(vscode.Uri.joinPath(mediaRoot, name)).toString();
  const personalCute = {
    "avatar-app-icon.svg": mediaUri("personal_cute/avatar-app-icon.svg"),
    "avatar-badge.svg": mediaUri("personal_cute/avatar-badge.svg"),
    "avatar-fullface-glasses.svg": mediaUri("personal_cute/avatar-fullface-glasses.svg"),
    "avatar-fullface-icon.svg": mediaUri("personal_cute/avatar-fullface-icon.svg"),
    "avatar-fullface-realistic.svg": mediaUri("personal_cute/avatar-fullface-realistic.svg"),
    "avatar-glasses.svg": mediaUri("personal_cute/avatar-glasses.svg"),
    "avatar-line.svg": mediaUri("personal_cute/avatar-line.svg"),
    "avatar-outline-premium.svg": mediaUri("personal_cute/avatar-outline-premium.svg"),
    "avatar-profile-card.svg": mediaUri("personal_cute/avatar-profile-card.svg"),
    "avatar-realistic-vector.svg": mediaUri("personal_cute/avatar-realistic-vector.svg"),
    "avatar-set-01-soft-studio.svg": mediaUri("personal_cute/avatar-set-01-soft-studio.svg"),
    "avatar-set-02-glasses-office.svg": mediaUri("personal_cute/avatar-set-02-glasses-office.svg"),
    "avatar-set-03-dark-badge.svg": mediaUri("personal_cute/avatar-set-03-dark-badge.svg"),
    "avatar-set-04-minimal-line.svg": mediaUri("personal_cute/avatar-set-04-minimal-line.svg"),
    "avatar-set-05-green-jacket.svg": mediaUri("personal_cute/avatar-set-05-green-jacket.svg"),
    "avatar-set-06-white-shirt.svg": mediaUri("personal_cute/avatar-set-06-white-shirt.svg"),
    "avatar-set-07-warm-shop.svg": mediaUri("personal_cute/avatar-set-07-warm-shop.svg"),
    "avatar-set-08-side-angle.svg": mediaUri("personal_cute/avatar-set-08-side-angle.svg"),
    "avatar-set-09-blue-cap.svg": mediaUri("personal_cute/avatar-set-09-blue-cap.svg"),
    "avatar-set-10-yellow-bucket.svg": mediaUri("personal_cute/avatar-set-10-yellow-bucket.svg"),
    "avatar-set-11-noir-glasses.svg": mediaUri("personal_cute/avatar-set-11-noir-glasses.svg"),
    "avatar-set-12-circular-clean.svg": mediaUri("personal_cute/avatar-set-12-circular-clean.svg"),
    "avatar-set-13-id-photo.svg": mediaUri("personal_cute/avatar-set-13-id-photo.svg"),
    "avatar-set-14-flat-sticker.svg": mediaUri("personal_cute/avatar-set-14-flat-sticker.svg"),
    "avatar-set-15-tech-avatar.svg": mediaUri("personal_cute/avatar-set-15-tech-avatar.svg"),
    "avatar-set-16-high-contrast.svg": mediaUri("personal_cute/avatar-set-16-high-contrast.svg"),
    "avatar-set-17-soft-square.svg": mediaUri("personal_cute/avatar-set-17-soft-square.svg"),
    "avatar-set-18-pencil-wash.svg": mediaUri("personal_cute/avatar-set-18-pencil-wash.svg"),
    "avatar-set-19-cropped-closeup.svg": mediaUri("personal_cute/avatar-set-19-cropped-closeup.svg"),
    "avatar-set-20-hero-gradient.svg": mediaUri("personal_cute/avatar-set-20-hero-gradient.svg"),
    "avatar-side-lit.svg": mediaUri("personal_cute/avatar-side-lit.svg"),
  };
  const roleAvatar = {
    ...personalCute,
    "robot-green-smile.svg": personalCute["avatar-set-15-tech-avatar.svg"],
    "robot-green-wheels.svg": personalCute["avatar-set-08-side-angle.svg"],
    "robot-green-simple.svg": personalCute["avatar-set-12-circular-clean.svg"],
    "robot-green-chat.svg": personalCute["avatar-profile-card.svg"],
    "robot-green-nano.svg": personalCute["avatar-set-16-high-contrast.svg"],
    "robot-yellow-face.svg": personalCute["avatar-badge.svg"],
    "robot-yellow-antenna.svg": personalCute["avatar-set-13-id-photo.svg"],
    "robot-yellow-eyes.svg": personalCute["avatar-fullface-glasses.svg"],
    "robot-yellow-wrench.svg": personalCute["avatar-set-04-minimal-line.svg"],
    "default": personalCute["avatar-app-icon.svg"],
  };
  return {
    hero: personalCute["avatar-set-20-hero-gradient.svg"],
    board: personalCute["avatar-profile-card.svg"],
    intervention: personalCute["avatar-set-03-dark-badge.svg"],
    spotlight: personalCute["avatar-side-lit.svg"],
    timeline: personalCute["avatar-line.svg"],
    rest: personalCute["avatar-set-17-soft-square.svg"],
    planning: personalCute["avatar-set-04-minimal-line.svg"],
    tooling: personalCute["avatar-set-15-tech-avatar.svg"],
    editing: personalCute["avatar-set-02-glasses-office.svg"],
    testing: personalCute["avatar-set-12-circular-clean.svg"],
    waiting: personalCute["avatar-set-01-soft-studio.svg"],
    alertPlink: mediaUri("Small object dropping into water with a distinct plink sound.mp3"),
    alertSplashes: mediaUri("Multiple small items falling into water, light and scattered splashes.mp3"),
    alertNature: mediaUri("nature ambience.mp3"),
    alertFnaf: mediaUri("fnaf 2 ambience.mp3"),
    personalCute,
    roleAvatar,
    agentRobot: roleAvatar,
  };
}

module.exports = {
  createWebviewMedia,
};
